name: crypto_challenge
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  flutter_dotenv: ^5.2.1 
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  get_it: ^8.0.3
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  liquid_pull_to_refresh: ^3.0.1
  flutter_svg: ^2.0.17
  intl: ^0.20.1
  chart_sparkline: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
